Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'lib/tasks/test.rake'
    - 'lib/tasks/cucumber.rake'
    - 'features/support/env.rb'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Max: 110
